amqp:
  host: "shrimp.rmq.cloudamqp.com"
  port: "5672"
  virtualHost: "***REMOVED***"
  username: "***REMOVED***"
  password: "***REMOVED***"
  heartbeatTimeout: "60"
  publisher1:
    exchange: eip-pub_sub
  listener1:
    queue: backend1-person
  listener2:
    queue: backend2-person
    
amq:
  url: "https://mq-us-east-1.anypoint.mulesoft.com/api/v1"
  client_id: "***REMOVED***"
  client_secret: "***REMOVED***"
  publisher1:
    exchange: eip-pubsub
  listener1:
    queue: backend1-person
  listener2:
    queue: backend2-person
  
http:
  listener:
    basepath: "/pub_sub"
    port: "8081"
    
api:
  id: "***REMOVED***"